### ISSUE TITLE
Request: Add a LICENSE file, please.

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlightjs-robot#2]

**Comment by Harri** [comment]
I'm currently vacationing but I'll add it after the holidays. Thanks.

**Comment by joshgoebel** [comment]
Happy Holidays!  Thanks!

**Comment by Harri** [comment]
Added 3 clause BSD license, which maches the parent project license. Personally I have no opinion on which permissive license to use.

**Comment by joshgoebel** [comment]
Awesome! Thanks.
